# Generated by Django 3.2.9 on 2021-12-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('drug_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'drug_num',
                'unique_together': {('country_id', 'year', 'drug_id')},
            },
        ),
        migrations.CreateModel(
            name='DrugGender',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('gender_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'gender_num',
                'unique_together': {('country_id', 'year', 'gender_id')},
            },
        ),
        migrations.CreateModel(
            name='DrugCountry',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'country_year_num',
                'unique_together': {('country_id', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DrugAge',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('age_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'age_num',
                'unique_together': {('country_id', 'year', 'age_id')},
            },
        ),
    ]
