# Generated by Django 3.2.6 on 2021-11-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newtitle', models.CharField(max_length=200)),
                ('Newsurl', models.URLField()),
            ],
        ),
    ]
