# Generated by Django 3.2.6 on 2021-11-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrugNews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslist',
            old_name='Newtitle',
            new_name='Newstitle',
        ),
    ]
